version: "1"
services:
  minerva:
    container_name: minerva:latest
    build:
      context: ..
      dockerfile: mongo/Dockerfile
    ports:
      - "5000:5000"

# https://docs.docker.com/compose/compose-file/